### ISSUE TITLE
shimv2 errors when using a helper script to set KATA_CONF_FILE

### ISSUE THREAD

**Issue by fidencio** [kata-containers/runtime#2616]
# Description of problem

When using the following script to call as a helper to call shimv2, I cannot start a pod.
```
fidencio@dahmer ~/src/fedora/kata-runtime $ cat containerd-shim-kataqemu-v2 
#!/bin/bash

KATA_CONF_FILE=/usr/share/kata-containers/defaults/configuration.toml /usr/bin/containerd-shim-kata-v2 $@
```
Note: This is totally related to https://github.com/kata-containers/runtime/issues/2610.

# Expected result

shimv2 would work in the same way as if the configuration file was in one of the canonical locations and `/usr/bin/containerd-shim-kata-v2` was called directly.

# Actual result

```
Failed to create pod sandbox: rpc error: code = Unknown desc = io.containerd.kata.v2: file file+net socket: setnonblock: bad file descriptor : exit status 1
```

It's important to note that if I create `/etc/kata-containers` and move the very same `configuration.toml` that I'm pointing to when using the script, everything will just work as expected.

It may be an issue in CRI-O as well, but for now I'm opening this one here and will point it to CRI-O folks as well.

**Comment by jodh-intel** [comment]
This appears to have been solved by https://github.com/kata-containers/runtime/pull/1173.

**Comment by ariel-adam** [comment]
@fidencio does the patch above solve the problem?

**Comment by fidencio** [comment]
No the patch does not solve the issue. This issue was open on Apr 2020, using upstream (at that time) runtime. The patch mentioned above is way older than the issue, and was already merged when this one was opened.

**Comment by jodh-intel** [comment]
@fidencio - shouldn't your script `exec containerd-shim-kata-v2` to avoid the extra process (for `bash`)?
